### ISSUE TITLE
Real password in console

### ISSUE THREAD

**Issue by sergeisnitko** [koltyakov/SPAuthN#3]
If we use *--forcePrompts=true* param to force the params in console, it shows the real password. It is not a good solution. Somebody can stay behind and catch by password by eye

![image](https://user-images.githubusercontent.com/7835251/32158678-099873f2-bd5b-11e7-9cf0-60c98415dc13.png)

**Comment by koltyakov** [comment]
Thanks! I'll take a look into this.

**Comment by koltyakov** [comment]
This is fixed now.
Please try uninstalling and installing nuget.
As the fix is related to Node.js dependency SPAuthN nuget version stays the same.
