### ISSUE TITLE
configPath in Options

### ISSUE THREAD

**Issue by sergeisnitko** [koltyakov/SPAuthN#4]
It would be great to have a path to current config file in Options object, that returns after auth. 

If we pass the param --configFile, we can parse it in our application and add custom properties in it. But if we use the default one, we don't know what config file will be used.

Thanks!

**Comment by koltyakov** [comment]
Thanks for posting the offer, yep, it would be cool to have this setting. 
Will apply corresponding changes shortly.

**Comment by koltyakov** [comment]
Have updated the NuGet. Please check ver 1.0.7.

**Comment by koltyakov** [comment]
Closing this.
